USE damai_order_1;

CREATE TABLE `d_order_ticket_user_record_0` (
  `id` bigint(20) NOT NULL COMMENT '主键id',
  `order_number` bigint(20) NOT NULL COMMENT '订单编号',
  `identifier_id` bigint(20) DEFAULT NULL COMMENT '记录id',
  `ticket_user_order_id` bigint(20) NOT NULL COMMENT '购票人订单id',
  `program_id` bigint(20) NOT NULL COMMENT '节目表id',
  `user_id` bigint(20) NOT NULL COMMENT '用户id',
  `ticket_user_id` bigint(20) NOT NULL COMMENT '购票人id',
  `seat_id` bigint(20) NOT NULL COMMENT '座位id',
  `seat_info` varchar(100) DEFAULT NULL COMMENT '座位信息',
  `ticket_category_id` bigint(20) DEFAULT NULL COMMENT '节目票档id',
  `order_price` decimal(10,0) DEFAULT NULL COMMENT '订单价格',
  `record_type_code` int(3) DEFAULT NULL COMMENT '记录类型编码 -1:扣减余票 0:改变状态 1:增加余票',
  `record_type_value` varchar(256) DEFAULT NULL COMMENT '记录类型值 -1:扣减余票(reduce) 0:改变状态(changeStatus) 1:增加余票(increase)',
  `reconciliation_status` int(3) DEFAULT '1' COMMENT '对账状态 1:未对账 -1:对账完成有问题 1:对账完成没有问题 2:对账有问题处理完毕',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
  `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
  PRIMARY KEY (`id`),
  KEY `d_order_ticket_user_record_order_id_IDX` (`order_number`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_order_id_IDX` (`ticket_user_order_id`) USING BTREE,
  KEY `d_order_ticket_user_record_user_id_IDX` (`user_id`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_id_IDX` (`ticket_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购票人订单记录表';

CREATE TABLE `d_order_ticket_user_record_1` (
  `id` bigint(20) NOT NULL COMMENT '主键id',
  `order_number` bigint(20) NOT NULL COMMENT '订单编号',
  `identifier_id` bigint(20) DEFAULT NULL COMMENT '记录id',
  `ticket_user_order_id` bigint(20) NOT NULL COMMENT '购票人订单id',
  `program_id` bigint(20) NOT NULL COMMENT '节目表id',
  `user_id` bigint(20) NOT NULL COMMENT '用户id',
  `ticket_user_id` bigint(20) NOT NULL COMMENT '购票人id',
  `seat_id` bigint(20) NOT NULL COMMENT '座位id',
  `seat_info` varchar(100) DEFAULT NULL COMMENT '座位信息',
  `ticket_category_id` bigint(20) DEFAULT NULL COMMENT '节目票档id',
  `order_price` decimal(10,0) DEFAULT NULL COMMENT '订单价格',
  `record_type_code` int(3) DEFAULT NULL COMMENT '记录类型编码 -1:扣减余票 0:改变状态 1:增加余票',
  `record_type_value` varchar(256) DEFAULT NULL COMMENT '记录类型值 -1:扣减余票(reduce) 0:改变状态(changeStatus) 1:增加余票(increase)',
  `reconciliation_status` int(3) DEFAULT '1' COMMENT '对账状态 1:未对账 -1:对账完成有问题 1:对账完成没有问题 2:对账有问题处理完毕',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
  `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
  PRIMARY KEY (`id`),
  KEY `d_order_ticket_user_record_order_id_IDX` (`order_number`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_order_id_IDX` (`ticket_user_order_id`) USING BTREE,
  KEY `d_order_ticket_user_record_user_id_IDX` (`user_id`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_id_IDX` (`ticket_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购票人订单记录表';

CREATE TABLE `d_order_ticket_user_record_2` (
  `id` bigint(20) NOT NULL COMMENT '主键id',
  `order_number` bigint(20) NOT NULL COMMENT '订单编号',
  `identifier_id` bigint(20) DEFAULT NULL COMMENT '记录id',
  `ticket_user_order_id` bigint(20) NOT NULL COMMENT '购票人订单id',
  `program_id` bigint(20) NOT NULL COMMENT '节目表id',
  `user_id` bigint(20) NOT NULL COMMENT '用户id',
  `ticket_user_id` bigint(20) NOT NULL COMMENT '购票人id',
  `seat_id` bigint(20) NOT NULL COMMENT '座位id',
  `seat_info` varchar(100) DEFAULT NULL COMMENT '座位信息',
  `ticket_category_id` bigint(20) DEFAULT NULL COMMENT '节目票档id',
  `order_price` decimal(10,0) DEFAULT NULL COMMENT '订单价格',
  `record_type_code` int(3) DEFAULT NULL COMMENT '记录类型编码 -1:扣减余票 0:改变状态 1:增加余票',
  `record_type_value` varchar(256) DEFAULT NULL COMMENT '记录类型值 -1:扣减余票(reduce) 0:改变状态(changeStatus) 1:增加余票(increase)',
  `reconciliation_status` int(3) DEFAULT '1' COMMENT '对账状态 1:未对账 -1:对账完成有问题 1:对账完成没有问题 2:对账有问题处理完毕',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
  `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
  PRIMARY KEY (`id`),
  KEY `d_order_ticket_user_record_order_id_IDX` (`order_number`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_order_id_IDX` (`ticket_user_order_id`) USING BTREE,
  KEY `d_order_ticket_user_record_user_id_IDX` (`user_id`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_id_IDX` (`ticket_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购票人订单记录表';


CREATE TABLE `d_order_ticket_user_record_3` (
  `id` bigint(20) NOT NULL COMMENT '主键id',
  `order_number` bigint(20) NOT NULL COMMENT '订单编号',
  `identifier_id` bigint(20) DEFAULT NULL COMMENT '记录id',
  `ticket_user_order_id` bigint(20) NOT NULL COMMENT '购票人订单id',
  `program_id` bigint(20) NOT NULL COMMENT '节目表id',
  `user_id` bigint(20) NOT NULL COMMENT '用户id',
  `ticket_user_id` bigint(20) NOT NULL COMMENT '购票人id',
  `seat_id` bigint(20) NOT NULL COMMENT '座位id',
  `seat_info` varchar(100) DEFAULT NULL COMMENT '座位信息',
  `ticket_category_id` bigint(20) DEFAULT NULL COMMENT '节目票档id',
  `order_price` decimal(10,0) DEFAULT NULL COMMENT '订单价格',
  `record_type_code` int(3) DEFAULT NULL COMMENT '记录类型编码 -1:扣减余票 0:改变状态 1:增加余票',
  `record_type_value` varchar(256) DEFAULT NULL COMMENT '记录类型值 -1:扣减余票(reduce) 0:改变状态(changeStatus) 1:增加余票(increase)',
  `reconciliation_status` int(3) DEFAULT '1' COMMENT '对账状态 1:未对账 -1:对账完成有问题 1:对账完成没有问题 2:对账有问题处理完毕',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `edit_time` datetime DEFAULT NULL COMMENT '编辑时间',
  `status` tinyint(1) DEFAULT '1' COMMENT '1:正常 0:删除',
  PRIMARY KEY (`id`),
  KEY `d_order_ticket_user_record_order_id_IDX` (`order_number`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_order_id_IDX` (`ticket_user_order_id`) USING BTREE,
  KEY `d_order_ticket_user_record_user_id_IDX` (`user_id`) USING BTREE,
  KEY `d_order_ticket_user_record_ticket_user_id_IDX` (`ticket_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购票人订单记录表';